# Generated by Django 2.1.5 on 2019-02-11 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False, verbose_name='Name')),
                ('icon', models.URLField(blank=True, verbose_name='Icon')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, verbose_name='Slug')),
                ('manual_rank', models.SmallIntegerField(blank=True, null=True, unique=True, verbose_name='ManualRank')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('affiliate_link', models.URLField(blank=True, null=True, verbose_name='AffiliateLink')),
                ('code', models.CharField(blank=True, max_length=70, null=True, verbose_name='OfferCode')),
                ('expiry_date', models.DateTimeField(verbose_name='ExpiryDate')),
                ('is_while_stocks_last', models.BooleanField(default=False, verbose_name='WhileStocksLast')),
                ('label', models.CharField(blank=True, choices=[('CODE', 'Offer Code'), ('SALE', 'Sale')], max_length=11, null=True, verbose_name='Label')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Terms')),
                ('external_id', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='ExternalID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponfinder.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False, verbose_name='Name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.URLField(blank=True, verbose_name='Logo')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, verbose_name='Slug')),
                ('category', models.ManyToManyField(to='couponfinder.Category')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponfinder.Organization'),
        ),
    ]
