# Generated by Django 2.1.5 on 2019-09-21 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Name')),
                ('icon', models.URLField(blank=True, verbose_name='Icon')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, verbose_name='Slug')),
                ('manual_rank', models.SmallIntegerField(blank=True, null=True, unique=True, verbose_name='ManualRank')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_country_code', models.SlugField(max_length=2, unique=True, verbose_name='IsoCountryCode')),
                ('flag', models.URLField(blank=True, null=True, verbose_name='FlagFilename')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('affiliate_link', models.URLField(blank=True, max_length=800, null=True, verbose_name='AffiliateLink')),
                ('link', models.URLField(blank=True, max_length=800, null=True, verbose_name='Link')),
                ('code', models.CharField(blank=True, max_length=70, null=True, verbose_name='OfferCode')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='StartDate')),
                ('expiry_date', models.DateTimeField(verbose_name='ExpiryDate')),
                ('is_while_stocks_last', models.BooleanField(default=False, verbose_name='WhileStocksLast')),
                ('label', models.CharField(blank=True, choices=[('CODE', 'Offer Code'), ('SALE', 'Sale')], max_length=11, null=True, verbose_name='Label')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Terms')),
                ('exclusive', models.BooleanField(default=False, verbose_name='Exclusive')),
                ('exclude', models.BooleanField(default=False, verbose_name='Exclude')),
                ('external_id', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='ExternalID')),
                ('source', models.CharField(blank=True, choices=[('AWIN', 'AWIN'), ('CJ', 'CJ')], max_length=11, null=True, verbose_name='Source')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponfinder.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponfinder.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Missing Organization Name', max_length=70, unique=True, verbose_name='Name')),
                ('slogan', models.TextField(blank=True, null=True, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('affiliate_link', models.URLField(blank=True, verbose_name='AffiliateLink')),
                ('logo', models.URLField(blank=True, verbose_name='Logo')),
                ('external_logo', models.URLField(blank=True, verbose_name='ExternalLogo')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, verbose_name='Slug')),
                ('program_joined', models.BooleanField(default=False, verbose_name='ProgramJoined')),
                ('exclude', models.BooleanField(default=False, verbose_name='Exclude')),
                ('external_id', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='ExternalID')),
                ('source', models.CharField(blank=True, choices=[('AWIN', 'AWIN'), ('CJ', 'CJ')], max_length=11, null=True, verbose_name='Source')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponfinder.Country')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponfinder.Organization'),
        ),
    ]
