# Generated by Django 2.1.5 on 2019-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='AffiliateLink'),
        ),
    ]
