# Generated by Django 2.1.5 on 2019-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_country_code', models.SlugField(blank=True, max_length=2, null=True, verbose_name='IsoCountryCode')),
                ('flag', models.URLField(blank=True, verbose_name='Flag')),
            ],
        ),
    ]
