# Generated by Django 2.1.5 on 2019-04-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0002_flags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flags',
            new_name='Flag',
        ),
    ]
