# Generated by Django 2.1.5 on 2019-10-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0002_auto_20191011_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_coupon',
            field=models.BooleanField(default=False, verbose_name='IsCoupon'),
        ),
    ]
