# Generated by Django 2.1.5 on 2020-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0003_offer_is_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_reviewed',
            field=models.DateField(blank=True, null=True, verbose_name='LastReviewed'),
        ),
    ]
