# Generated by Django 2.1.5 on 2020-02-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0004_organization_last_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='source',
            field=models.CharField(blank=True, choices=[('AWIN', 'AWIN'), ('CJ', 'CJ'), ('C_MVC', 'C_MVC')], max_length=11, null=True, verbose_name='Source'),
        ),
    ]
