# Generated by Django 2.1.5 on 2019-04-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0004_auto_20190428_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Country'),
        ),
    ]
