# Generated by Django 2.1.5 on 2019-05-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0005_flag_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flag',
            new_name='Country',
        ),
    ]
