# Generated by Django 2.1.5 on 2019-05-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0006_auto_20190505_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='flag_filename',
            new_name='flag',
        ),
    ]
