# Generated by Django 2.1.5 on 2019-05-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponfinder', '0008_offer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(default='GB', on_delete=django.db.models.deletion.CASCADE, to='couponfinder.Country'),
            preserve_default=False,
        ),
    ]
